# -*- coding: utf-8 -*-
"""Abeera-AI-LinkedIn-Post-Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pbqtX6PqAHmiII254wViPeV6Zld7MZKO

## **Abeera AI LinkedIn Post Generator 🚀**

This project is an AI-powered LinkedIn content generator built using **Gradio** and the Groq API. It helps users quickly create engaging, professional, and high-quality LinkedIn posts with just a few inputs.

The application allows users to enter a topic, select a tone (such as professional, inspirational, or storytelling), and choose the desired length of the post. Based on these inputs, the AI generates well-structured content with a strong opening hook, relevant messaging, and a clear call to action.

This project demonstrates practical implementation of:

* AI-powered text generation
* Prompt engineering techniques
* Interactive UI development using Gradio
* API integration for real-time content generation

It is designed as a beginner-friendly yet impactful project for students and professionals interested in **AI, content creation, and automation**.

## 🎯 Key Features

* Generate LinkedIn posts instantly
* Multiple tone options (professional, casual, inspirational, storytelling)
* Adjustable content length (short, medium, long)
* Clean and interactive web interface using Gradio
* Fast and efficient AI responses via Groq API


## 💡 Use Cases

* Personal branding on LinkedIn
* Showcasing projects and achievements
* Writing professional updates effortlessly
* Content creation for students and professionals


## 🧠 Technologies Used

* Python
* Gradio
* Groq API
* LLM (LLaMA-based model)

## ✨ Author

**Abeera Iftikhar**
"""

!pip install gradio groq

import os
os.environ["GROQ_API_KEY"] = "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"

from groq import Groq

client = Groq(api_key="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")

def generate_post(topic, tone, length):
    prompt = f"""
    Write a professional LinkedIn post.

    Topic: {topic}
    Tone: {tone}
    Length: {length}

    Make it engaging, human-like, and suitable for LinkedIn.
    Add emojis where appropriate.
    Include a strong hook and a call to action.
    """

    response = client.chat.completions.create(
        model="llama3-70b-8192",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7,
    )

    return response.choices[0].message.content

import gradio as gr

interface = gr.Interface(
    fn=generate_post,
    inputs=[
        gr.Textbox(label="Post Topic"),
        gr.Dropdown(["Professional", "Casual", "Inspirational", "Storytelling"], label="Tone"),
        gr.Dropdown(["Short", "Medium", "Long"], label="Length"),
    ],
    outputs=gr.Textbox(label="Generated LinkedIn Post"),
    title="Abeera AI LinkedIn Post Generator 🚀",
    description="Generate LinkedIn posts using AI",
)

interface.launch(share=True)